version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: go_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_backend
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: