server:
  port: 8002
database:
  - user: admin
    password: admin
    host: localhost
    dbName: db
  - user: root
    password: root
    host: localhost
    dbName: order
sercurity:
  jwt:
    key: docongthanhphuong
redis:
  user: admin
elasticsearch:
  user: admin
rabbitMQ:
  user: admin
kafka:
  user: admin
